version: '3.6'

services:
  python-lambda:
    container_name: python-lambda
    build: .
    volumes:
      - $HOME/.aws/:/root/.aws/
      - ./output/:/var/task/output/
    ports:
      - '8000:8080'
    env_file:
      - .env
